import { prisma } from "@/lib/prisma";
import { getActorId } from "@/lib/actor";
import { logActivity } from "@/lib/activityLog";
import { buildStorageRelativePath, saveDocumentFile, computeSha256 } from "@/lib/documents/storage";
import { renderComputationSheetHtml } from "@/lib/documents/computationSheetHtml";
import { assembleAndComputeFiling } from "@/lib/filingComputation";
import type { FilingComputationResult, Period } from "@/lib/tax/types";

const DRAFT_COMPUTATION_SLOT = "draft_computation";
const PREPARE_RETURN_STEP = "PREPARE_RETURN";
export const AUTO_GENERATED_NOTE = "Auto-generated by the app from the computation sheet — no upload.";

/**
 * Rework brief §5.4 — ensures the PREPARE_RETURN step's draft_computation
 * slot holds the app's own rendered computation sheet, with no user
 * upload involved. Idempotent and cheap to call from wherever the
 * bookkeeper interacts with step 3 (marking it in progress/done, or the
 * receipts acknowledgement): once the filing is frozen (computationSnapshot
 * set), the saved file is never regenerated again — it matches the
 * immutable snapshot, same as the rest of a filed return. While unfrozen,
 * a fresh call replaces the previous auto-generated copy (soft-deleted,
 * not hard-deleted — it stays in the audit trail) with one reflecting
 * the current live figures, so the vault never holds a stale draft next
 * to a materially different live preview for long.
 */
export async function ensureComputationSheetSaved(filingId: string): Promise<{ documentId: string } | null> {
  const filing = await prisma.filing.findUnique({ where: { id: filingId }, include: { client: true } });
  if (!filing) return null;

  const step = await prisma.workflowStep.findFirst({
    where: { filingId, stepCode: PREPARE_RETURN_STEP },
  });
  if (!step) return null;

  const isFrozen = filing.computationSnapshot != null;

  const existingAutoDoc = await prisma.document.findFirst({
    where: { workflowStepId: step.id, docSlotCode: DRAFT_COMPUTATION_SLOT, notes: AUTO_GENERATED_NOTE, deletedAt: null },
    orderBy: { uploadedAt: "desc" },
  });

  // Frozen and already has its saved copy: never regenerate — it must
  // keep matching the immutable snapshot, same rule as computationSnapshot
  // itself (SPEC.md 5).
  if (isFrozen && existingAutoDoc) {
    return { documentId: existingAutoDoc.id };
  }

  const sheet: FilingComputationResult = isFrozen
    ? (JSON.parse(filing.computationSnapshot as string) as FilingComputationResult)
    : await assembleAndComputeFiling(filing.clientId, filing.taxableYear, filing.period as Period);

  const generatedAt = new Date();
  const html = renderComputationSheetHtml({
    clientName: filing.client.registeredName,
    clientTin: filing.client.tin,
    taxableYear: filing.taxableYear,
    period: filing.period,
    sheet,
    isFrozen,
    generatedAt,
  });
  const buffer = Buffer.from(html, "utf-8");
  const sha256 = computeSha256(buffer);

  // Nothing changed since the last auto-generated copy (same content) —
  // avoid piling up identical versions on every touch of step 3.
  if (existingAutoDoc && existingAutoDoc.sha256 === sha256) {
    return { documentId: existingAutoDoc.id };
  }

  const existingCount = await prisma.document.count({
    where: { filingId: filing.id, docSlotCode: DRAFT_COMPUTATION_SLOT, deletedAt: null },
  });

  const relativePath = buildStorageRelativePath({
    clientCode: filing.client.code,
    taxableYear: filing.taxableYear,
    period: filing.period,
    stepCode: PREPARE_RETURN_STEP,
    slotCode: DRAFT_COMPUTATION_SLOT,
    documentDate: generatedAt,
    seq: existingCount + 1,
    ext: "html",
  });
  await saveDocumentFile(relativePath, buffer);

  const actorId = await getActorId();

  if (existingAutoDoc) {
    await prisma.document.update({
      where: { id: existingAutoDoc.id },
      data: { deletedAt: generatedAt, deletedReason: "Superseded by a freshly generated computation sheet.", actorId },
    });
  }

  const created = await prisma.document.create({
    data: {
      clientId: filing.clientId,
      filingId: filing.id,
      workflowStepId: step.id,
      docSlotCode: DRAFT_COMPUTATION_SLOT,
      category: "COMPUTATION_SHEET",
      originalFilename: `computation-sheet-${filing.taxableYear}-${filing.period}.html`,
      storedPath: relativePath,
      mimeType: "text/html",
      sizeBytes: buffer.byteLength,
      sha256,
      documentDate: generatedAt,
      notes: AUTO_GENERATED_NOTE,
      actorId,
    },
  });

  await logActivity({ entityType: "Document", entityId: created.id, action: "CREATE", after: created, actorId });

  return { documentId: created.id };
}
